# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_variants', models.PositiveIntegerField()),
                ('number_3utr_variants', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Job')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Prediction')),
            ],
        ),
    ]
