# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_job_jobpredictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPredictions',
            new_name='JobPrediction',
        ),
    ]
