# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171218_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TranscriptAnnotation'),
        ),
        migrations.AddField(
            model_name='variant',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gene'),
        ),
    ]
