FROM postgres

#ADD postgresql.conf /var/lib/postgresql/data/postgresql.conf
#ADD pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
#RUN chown postgres:postgres /var/lib/postgresql/data/*.conf

EXPOSE 5432